### ISSUE TITLE
Lock (music) track against (ripple) cut

### ISSUE THREAD

**Issue by nitramred** [Ultraschall/ultraschall-plugin#19]
As discussed with @mespotine it would be great to lock one or more tracks against any kind of editing. I often use music with my podcasts and it's a big source of error if I edit out an "ähm" in the intro only to realize that the intro music was shortened as well. Thanks in advance!

**Comment by heikopanjas** [comment]
Wrong repo. Please refile @ https://github.com/Ultraschall/ultraschall-portable.
