### ISSUE TITLE
Clarify build requirements / supported build targets

### ISSUE THREAD

**Issue by lootsy** [Ultraschall/ultraschall-plugin#3]
It seems there are old docs describing an older state.

Delete obsolete files or obsolete content in files.
Describe / document the current state for building the code in this repo.

quote / assumption / guess....:
```
supported:
- Xcode@macOS
- VS2019@Windows
- gcc@Ubuntu/Arch/Azure/WSL. 
```

**Comment by heikopanjas** [comment]
Duplicate of issue #2
