### ISSUE TITLE
Add "good" .gitattributes file to repo

### ISSUE THREAD

**Issue by lootsy** [Ultraschall/ultraschall-plugin#4]
I tried to build the code under Arch Linux.
My git config was set by `git config --global core.autocrlf true` (I copied my configuration from my Win workstation).
This setting does not make much sense for linux.

With this setting I get the following error:
```
[lootsy@arch ultraschall-plugin-old (feature/try-to-build-on-arch $)]$ ./bootstrap.sh 
bash: ./bootstrap.sh: /bin/bash^M: bad interpreter: No such file or directory
[lootsy@arch ultraschall-plugin-old (feature/try-to-build-on-arch $)]$ 
```

This error I saw the last time in the 90's when I worked with Mac and Win simultaneously.
I think the problem with line endings one can avoid with a "good" `.gitattributes` file __in__ the repo.

I suggest only one line: `* text=auto`

Maybe there's a better ("good") solution.

I changed my git config with `git config --global core.autocrlf input` and cloned the repo again.
After that the problem with line ending disappeared.

**Comment by heikopanjas** [comment]
Done.
